name: python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Check out nomad
      uses: actions/checkout@v3
      with:
        repository: nomad-coe/nomad
        path: nomad
        submodules: true
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[tests]
        pip install ./nomad[parsing]
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 *parsers tests
    - name: pylint
      run: |
        python -m pylint *parsers tests
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional *parsers tests
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
